{{- if eq .Values.AwsRegion .Values.AwsRegion1 }}
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/agent-inject-template-db-creds: |
    {{- with .Values.vaultPostgresTemplate }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- else }}
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/agent-inject-template-db-creds: |
    {{- with .Values.vaultPostgresTemplate }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end}}
