apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.<assetId>Svc.Id }}-{{ Values.AbbreviatedEnv }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sample-application.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "sample-application.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sample-application.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sample-application.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.xk7469Svc.Id }}-{{ Values.AbbreviatedEnv }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.<assetId>Svc.Image }}:{{ .Values.<assetId>Svc.ImageTag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.<assetId>Svc.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: PDM_UUID
              value: {{ .Values.pdmUuid }}
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.spring.profiles.active }}
        - name: filebeat
          image: "{{ .Values.filebeat.image }}:{{ .Values.filebeat.imageTag }}"
          imagePullPolicy: {{ .Values.filebeat.pullPolicy }}
          args: [
            "-c", "/etc/filebeat.yml",
            "-e",
          ]
          volumeMounts:
            - name: config
              mountPath: /etc/filebeat.yml
              subPath: filebeat.yml
          resources:
            {{- toYaml .Values.filebeat.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "sample-application.fullname" . }}-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
